name: MCDevTools
version: '${version}'
main: com.ericlmao.tools.MCDevToolsPlugin
api-version: '1.21'
authors: ["ericlmao"]
dependencies:
  server:
    PlaceholderAPI:
      load: AFTER
      required: false
